version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for npm dependencies in the root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Group all dependencies together
    groups:
      all-dependencies:
        patterns:
          - "*"

  # Enable version updates for each package
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/packages/admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/packages/mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
