# Configuration for GitHub repository

# Set default branch name to 'main'
repository:
  name: AliveHuman
  default_branch: main
  description: "A comprehensive platform with web, admin, and mobile applications built on a monorepo architecture."
  homepage: "https://alivehuman.com"
  topics:
    - typescript
    - nestjs
    - nextjs
    - react-native
    - monorepo
    - blockchain
    - web3
    - polygon
  
# Labels configuration
labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"

# Branch protection rules
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
        contexts: ["lint", "test", "build"]
      enforce_admins: true
      restrictions: null
